### PR TITLE
dumpling: remove a confusing log

### LINKED ISSUE #1066: misleading log in dumpling for extra-args
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    start a task with `extra-args` in `mydumpers` section.

2. What did you expect to see?

3. What did you see instead?

    `[2020/09/18 19:56:36.123 +08:00] [WARN] [dumpling.go:262] ["meeting some unsupported arguments"] [task=pupu-qa_log] [unit=dump] [argument="[--skip-tz-utc,-B,tmp,-T,allocationdifferencenotes]"]`

    only `--skip-tz-utc` is unsupported, but the log may let the user think `-B`/`-T` are also unsupported.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-rc.2
        ```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1066

### What is changed and how it works?
we already printed unsupported arguments in https://github.com/pingcap/dm/blob/ff03ee6f6951f570099c19cb84e5497e2822ce21/dumpling/dumpling.go#L250 , so remove this printing

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/run-all-tests

pod failed

**Pull request merged**
