### PR TITLE
dep: update tidb (fix print massive log) and parser

### PR DESCRIPTION
**Pull request by lance6716**
### What is changed and how it works?
port TiDB https://github.com/pingcap/tidb/pull/18844

update parser to https://github.com/pingcap/tidb/blob/f82e5320ad75442f8f9dd76316ef20b1707386ee/go.mod#L39

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
note: could revert schema tracker part of #801 in this PR or another.

**Comment by csuzhangxc** [comment]
> note: could revert schema tracker part of #801 in this PR or another.

we can revert part of #801 later because not all of users will upgrade TiDB to the newest version recently.

**Comment by lance6716** [comment]
> > note: could revert schema tracker part of #801 in this PR or another.
> 
> we can revert part of #801 later because not all of users will upgrade TiDB to the newest version recently.

Only the schema tracker part (updated PR comment). Downstream part will keep because auto-drop is triggered by downtream error message

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
