### PR TITLE
tests: remove `use-rowid` and `sql-mode` properties configuration of integration tests

### LINKED ISSUE #1435: tests: wrong configuration of all model integration test
## Bug Report

1. What did you do? If possible, provide a recipe for reproducing the error.

If you are doing integration tests, it will show us:

```
[2021/02/04 23:14:12.730 +08:00] [ERROR] [main.go:38] ["parse cmd flags"] [error="unknown keys in config file /dm/tests/all_mode/conf/diff_config.toml: [use-rowid source-db.sql-mode source-db.sql-mode]"] [errorVerbose="unknown keys in config file /dm/tests/all_mode/conf/diff_config.toml: [use-rowid source-db.sql-mode source-db.sql-mode]
main.(*Config).configFromFile
	/tidb-tools/sync_diff_inspector/config.go:282
main.(*Config).Parse
	/tidb-tools/sync_diff_inspector/config.go:248
main.main
	/tidb-tools/sync_diff_inspector/main.go:32
runtime.main
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/proc.go:204
runtime.goexit
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/asm_amd64.s:1374"] [stack="main.main
	/tidb-tools/sync_diff_inspector/main.go:38
runtime.main
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/proc.go:204"]
...
make: *** [integration_test] Error 1
```

2. What did you expect to see?

`make integration_test` exit 0

3. What did you see instead?

make: *** [integration_test] Error 1

4. Versions of the cluster

    - DM version:

        ```
        efa5b30ee9be9293305ab78a202484b0281ce169
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        5.7
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        Release Version: v4.0.0-beta.2-2053-g05d995d73-dirty
        Edition: Community
        Git Commit Hash: 05d995d73d236077cf8883e7950d650b7e4a50a5
        Git Branch: rel
        UTC Build Time: 2021-01-26 14:11:43
        GoVersion: go1.15.7
        Race Enabled: false
        TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
        Check Table Before Drop: false
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        no
        ```

    - Other interesting information (system version, hardware config, etc):

        >Darwin rmbp.local.cc 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by hidehalo**
### What problem does this PR solve?

resolve #1435

### What is changed and how it works?

remove `use-rowid` and `sql-mode` properties configuration of integration tests

### Check List 

Tests 

 - Integration test

Code changes

 - No

Side effects

-  No

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by hidehalo** [comment]
@lance6716 I don't get it, why this make `all_mode` test failed?

> [2021-02-09T10:09:50.360Z] [2021/02/09 18:09:47.838 +08:00] [ERROR] [diff.go:422] ["check failed"] [table=`all_mode`.`t2`] [error="line 1 column 17 near ""t2" (
> 
> [2021-02-09T10:09:50.360Z]   "id" int NOT NULL AUTO_INCREMENT,
> 
> [2021-02-09T10:09:50.360Z]   "name" varchar(20) DEFAULT NULL,
> 
> [2021-02-09T10:09:50.360Z]   PRIMARY KEY ("id")
> 
> [2021-02-09T10:09:50.360Z] ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci" "] [errorVerbose="line 1 column 17 near ""t2" (
> 
> [2021-02-09T10:09:50.360Z]   "id" int NOT NULL AUTO_INCREMENT,
> 
> [2021-02-09T10:09:50.360Z]   "name" varchar(20) DEFAULT NULL,
> 
> [2021-02-09T10:09:50.360Z]   PRIMARY KEY ("id")
> 
> [2021-02-09T10:09:50.360Z] ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci" 
> 
> [2021-02-09T10:09:50.360Z] github.com/pingcap/errors.AddStack
> 
> [2021-02-09T10:09:50.360Z] 	/home/jenkins/agent/workspace/build_tidb_tools_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174
> 
> [2021-02-09T10:09:50.360Z] github.com/pingcap/errors.Trace
> 
> [2021-02-09T10:09:50.360Z] 	/home/jenkins/agent/workspace/build_tidb_tools_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15
> 
> [2021-02-09T10:09:50.360Z] github.com/pingcap/parser.(*Parser).Parse
> 
> [2021-02-09T10:09:50.360Z] 	/home/jenkins/agent/workspace/build_tidb_tools_master/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20191223023445-b93660cf3e4e/yy_parser.go:146

**Comment by lance6716** [comment]
that seems a sql mode error. after we remove sql mode config, we rely on `sync diff` automatically finding right sql mode from upstream, but CI failed because it didn't see ANSI_QUOTES. I'll take a look later, or you could help me check that logic. 

could you reproduce it on your local PC? what's the version of `sync diff`

**Comment by hidehalo** [comment]
> that seems a sql mode error. after we remove sql mode config, we rely on `sync diff` automatically finding right sql mode from upstream, but CI failed because it didn't see ANSI_QUOTES. I'll take a look later, or you could help me check that logic.
> 
> could you reproduce it on your local PC? what's the version of `sync diff`

I get different error message in local PC:

> [2021/02/09 18:31:57.142 +08:00] [FATAL] [main.go:80] ["fail to initialize diff process"] [error="table all_mode.t2 in check tables not found"] [errorVerbose="table all_mode.t2 in check tables not found

tool version is:

```shell
~/D/O/dm (test) ./bin/sync_diff_inspector -V
version: 
sync_diff_inspector: v4.0.10-1-g4692c1e
Git Commit Hash: 4692c1e386b323a6f53378f10906bc480da2cb0c
Git Branch: master
UTC Build Time: 2021-01-26 03:09:29
Go Version: go1.15.7
```

**Comment by lance6716** [comment]
> > that seems a sql mode error. after we remove sql mode config, we rely on `sync diff` automatically finding right sql mode from upstream, but CI failed because it didn't see ANSI_QUOTES. I'll take a look later, or you could help me check that logic.
> > could you reproduce it on your local PC? what's the version of `sync diff`
> 
> I get different error message in local PC:
> 
> > [2021/02/09 18:31:57.142 +08:00] [FATAL] [main.go:80] ["fail to initialize diff process"] [error="table all_mode.t2 in check tables not found"] [errorVerbose="table all_mode.t2 in check tables not found
> 
> tool version is:
> 
> ```shell
> ~/D/O/dm (test) ./bin/sync_diff_inspector -V
> version: 
> sync_diff_inspector: v4.0.10-1-g4692c1e
> Git Commit Hash: 4692c1e386b323a6f53378f10906bc480da2cb0c
> Git Branch: master
> UTC Build Time: 2021-01-26 03:09:29
> Go Version: go1.15.7
> ```
> 
> PS: manually build on Mac OS X (Darwin rmbp.local.cc 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64)

our CI uses a very old version 😂

```
$ ./sync_diff_inspector -V
version:
sync_diff_inspector: v1.0.0~rc2+git.cccf51b
Git Commit Hash: cccf51b6f44cc6bbd96841d2fdc0c7bd9364ac69
UTC Build Time: 2020-02-27 05:46:50
Go Version: go1.13
```

we will update it later. And I think after we update CI this PR is needed. For now, please exclude the config file changes in this PR when `git add`. Thanks again

**Comment by hidehalo** [comment]
> > > that seems a sql mode error. after we remove sql mode config, we rely on `sync diff` automatically finding right sql mode from upstream, but CI failed because it didn't see ANSI_QUOTES. I'll take a look later, or you could help me check that logic.
> > > could you reproduce it on your local PC? what's the version of `sync diff`
> > 
> > 
> > I get different error message in local PC:
> > > [2021/02/09 18:31:57.142 +08:00] [FATAL] [main.go:80] ["fail to initialize diff process"] [error="table all_mode.t2 in check tables not found"] [errorVerbose="table all_mode.t2 in check tables not found
> > 
> > 
> > tool version is:
> > ```shell
> > ~/D/O/dm (test) ./bin/sync_diff_inspector -V
> > version: 
> > sync_diff_inspector: v4.0.10-1-g4692c1e
> > Git Commit Hash: 4692c1e386b323a6f53378f10906bc480da2cb0c
> > Git Branch: master
> > UTC Build Time: 2021-01-26 03:09:29
> > Go Version: go1.15.7
> > ```
> > 
> > 
> > PS: manually build on Mac OS X (Darwin rmbp.local.cc 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64)
> 
> our CI uses a very old version 😂
> 
> ```
> $ ./sync_diff_inspector -V
> version:
> sync_diff_inspector: v1.0.0~rc2+git.cccf51b
> Git Commit Hash: cccf51b6f44cc6bbd96841d2fdc0c7bd9364ac69
> UTC Build Time: 2020-02-27 05:46:50
> Go Version: go1.13
> ```
> 
> we will update it later. And I think after we update CI this PR is needed. For now, please exclude the config file changes in this PR when `git add`. Thanks again

🤣 Ok

**Comment by lance6716** [comment]
```
unknown keys in config file /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/tests/online_ddl/conf/diff_config.toml: [table-config.index-field]
```

```
error="unknown keys in config file /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/tests/import_v10x/conf/diff_config.toml: [source-db.sql-mode source-db.sql-mode]
```

please help remove these field in config files of sync diff

**Comment by lance6716** [comment]
> ```
> [table-config.index-field]
> ```
> 
> ```
> [source-db.sql-mode source-db.sql-mode]
> ```
> 
> please help remove these field in config files of sync diff.
> 
> I'll test new version of sync-diff in a CI sandbox. After all CI passes, I'll upgrade the official CI script

@hidehalo this is a CI sandbox https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8185/pipeline

**Comment by hidehalo** [comment]
> ```
> [table-config.index-field]
> ```
> 
> ```
> [source-db.sql-mode source-db.sql-mode]
> ```
> 
> please help remove these field in config files of sync diff.
> 
> I'll test new version of sync-diff in a CI sandbox. After all CI passes, I'll upgrade the official CI script

👌

**Comment by lance6716** [comment]
waiting https://github.com/pingcap/tidb-tools/pull/412 packed into nightly build

**Review by lance6716 — APPROVED** [review]
LGTM

**Pull request merged**
