### PR TITLE
Quality reinforcement(2): fix unstable test cases

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
fix unstable test cases in CI.

- [ ] testScheduler.TestScheduler, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6272/pipeline/70)
- [ ] ha: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6432/pipeline) [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6459/pipeline/71/)
   **root cause: leader client is not reflecting real time leader change, so there maybe two DM-master thinking the other is leader and cause forwarding loop**
- [x] sequence_sharding_optimistic: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6407/pipeline), [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6463/pipeline/71), lance6716, https://github.com/pingcap/dm/pull/959/commits/4a60e6b05cc7afe918a3bdcf1b285c1f8068f95e
- [ ] initial_unit: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6463/pipeline/80)
- [x] ~~load_interrupt: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6473/pipeline/81)~~
- [x] sequence_sharding_removemeta: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6473/pipeline/71), lance6716, https://github.com/pingcap/dm/pull/959/commits/3c2a847d2699ce4eee1d3503116f01c03a39ac28
- [x] shardddl3: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6474/pipeline), gmhdbjd, 8822679
- [x] ha_cases: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6476/pipeline), gmhdbjd, #985
- [ ] dmctl_basic: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6481/pipeline/75), gmhdbjd, #994 
- [x] DATA RACE: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/dm_ghpr_test/runs/6505/nodes/70/steps/369/log/?start=0), lance6716, https://github.com/pingcap/dm/pull/959/commits/27887eb92d42dd0f16bd83c52a9cfb7912adbc21
- [ ] testRelaySuite.TestProcess: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6525/pipeline/68)
- [x] ha_cases (worker offline): [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6535/pipeline/77), gmhdbjd, 89a1d8c
- [ ] testSubTask.TestSubTaskNormalUsage, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6546/pipeline)
- [ ] testMaster.TestOfflineMember, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6577/pipeline)

### What is changed and how it works?
- /run-all-tests to find unstable cases.
- push commit in this pr to fix the cases.

### CODE REVIEW

**Comment by csuzhangxc** [comment]
/run-all-tests

try to trigger update coverage to codecov.io

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
