### PR TITLE
config: support domain:port as well as ip:port

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
 support` domain:port` as well as `ip:port`, originally some URl parse will fail

### What is changed and how it works?
modify URL parse and config check

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
PTAL @lichunzhu

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
