### PR TITLE
*: use `IsRetryableError` in tidb-tools

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

replace `IsRetryableError` with the one in tidb-tools repo

### What is changed and how it works?

- update tidb-tools mod
- replace `IsRetryableError` usage

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@WangXiangUSTC @amyangfei PTAL

**Comment by WangXiangUSTC** [comment]
LGTM

**Pull request merged**
