### PR TITLE
gtid: fix bug that binlog name dosen't update after rotate

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 

fix issue https://github.com/pingcap/dm/issues/681

### What is changed and how it works?

update last location when current location >= last location

### Check List 

Tests 

 - Integration test

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@GMHDBJD PTAL

**Comment by csuzhangxc** [comment]
@WangXiangUSTC a fix for UT in #703.

**Comment by WangXiangUSTC** [comment]
> @WangXiangUSTC a fix for UT in #703.

ok, wait this or merged

**Pull request merged**
