### PR TITLE
syncer: update active relay log at fake rotate event

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 

in https://github.com/pingcap/dm/pull/1393, we support only specify GTID with no binlog filename, so we can't update active relay log filename at init time. Although active relay log will be updated when after `checkpoint-flush-interval` seconds and receiving an event, for the first `checkpoint-flush-interval` seconds, purge-relay will fail because of no active relay log, which may confuse user.

### What is changed and how it works?

when only specify GTID with no binlog filename, use fake rotate event to update active relay log.

also, add a integration test to make sure active relay log is forwarded when there's only DML

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported variable/fields change

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by lance6716** [comment]
in https://github.com/pingcap/dm/pull/1404, heartbeat is sent on 30 seconds no upstream events generated. But user configurates only sync DML, enables relay, and upstream keeps generating binlog events, maybe there's no chance to flush global checkpoint and update active relay log. Will check tomorrow

**Review by lichunzhu — COMMENTED** [review]
The integration test name only_dml is confusing. Personally suggest changing to purge_relay_active or something else.
Rest LGTM.

**Comment by lance6716** [comment]
> The integration test name only_dml is confusing. Personally suggest changing to purge_relay_active or something else.
> Rest LGTM.

this test aims covering a use case of only synchronize dml, which is specified in release testing doc.

**Review by lichunzhu — COMMENTED** [review]
/lgtm

**Review by GMHDBJD — APPROVED** [review]
/lgtm

**Pull request merged**
