### PR TITLE
feat: add get-config command (#1323)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1323 to release-2.0

---

### What problem does this PR solve? 
use get-config command to get task/worker/master/source cfg.

### What is changed and how it works?
- [x] refine get-task-config to support merge from subtask
- [x] get worker/master/source cfg

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by lance6716** [comment]
@GMHDBJD need resolve conflict

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
