### PR TITLE
fix: handle `null` table_info after importing from v1.0.x

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

    `gen delete sqls failed, schema: import_v10x, table: t2: Column count doesn't match value count: 0 (columns) vs 2 (values)` reported after importing from v1.0.6.

### What is changed and how it works?

   do not create an empty table if `table_info` column is `null`

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by lance6716** [comment]
how did test generate "null" tableinfo 🤔

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Comment by csuzhangxc** [comment]
> how did test generate "null" tableinfo 🤔

add `table_info` column will generate `null` value with json type.

**Comment by lance6716** [comment]
LGTM

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
