### PR TITLE
dmctl: add config err log

### LINKED ISSUE #1988: Improve log readability when dmctl is used incorrectly
## Feature Request

**Is your feature request related to a problem? Please describe:**

`dmctl check-task --config ./tes.yaml`

When using dmctl with the above incorrect command, the current error message is easy to misinterpret

image

**Describe the feature you'd like:**

Gives a more friendly hint, e.g. the current command parameter: `--config` is used incorrectly

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by jerrylisl**
### What problem does this PR solve? 
close #1988 

### What is changed and how it works?
dmctl will always try to parse --config(even it will not be used) and treat it as the dmctl config, that's the reason of err in this case, and if the --config is actually needed and can't be parsed correctly, it will cause the same err, add log to make it more readable

### Check List 

Tests 
 - No code

Code changes

Side effects

Related changes

### CODE REVIEW

**Review by lance6716 — COMMENTED** [review]
this `Annotatef` covers too many errors, for example, if `(Config).Adjust()` returned with "--master-addr not provided, this parameter is required when interacting with the dm-master, you can also use environment variable 'DM_MASTER_ADDR' to specify the value. Use `dmtcl --help` to see more help messages", we don't need this annotation.

I'd like to see move it to `(Config).configFromFile`

**Comment by jerrylisl** [comment]
> this `Annotatef` covers too many errors, for example, if `(Config).Adjust()` returned with "--master-addr not provided, this parameter is required when interacting with the dm-master, you can also use environment variable 'DM_MASTER_ADDR' to specify the value. Use `dmtcl --help` to see more help messages", we don't need this annotation.
> 
> I'd like to see move it to `(Config).configFromFile`

**Review by lance6716 — APPROVED** [review]

**Review by Ehco1996 — APPROVED** [review]
LGTM

@jerrylisl  Thanks for your contribution

**Pull request merged**
