### PR TITLE
loader, test: fix bug of clean dump file and update checkpoint

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
found ERROR in log, which caused by bug in https://github.com/pingcap/dm/pull/1027.

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch #1043

### CODE REVIEW

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by csuzhangxc** [comment]
/run-all-tests

rpc addr 127.0.0.1:8262 check alive timeout

**Comment by lance6716** [comment]
seems this PR should not cherry-pick to 1.0, because the root cause which was introduced in https://github.com/pingcap/dm/pull/1027 did not

**Pull request merged**
