### PR TITLE
relay: fix bug of relay metrics being recorded only once

### PR DESCRIPTION
**Pull request by reAsOn2010**
### What problem does this PR solve? 
https://asktug.com/t/topic/93363/7

### What is changed and how it works?
wrap the ticker listener in for loop so we can continuously receive the events.

### Check List 

Tests 

 - Manual test (TODO)

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by lance6716** [comment]
Thanks! Have you verified this fix by building DM and runing it?

**Comment by reAsOn2010** [comment]
> Thanks! Have you verified this fix by building DM and runing it?

I've tested it with some extra logging not included in this pr (only for test), and it seems ok
image

**Review by lance6716 — APPROVED** [review]

**Comment by reAsOn2010** [comment]
@lance6716 thanks, and when will v2.0.4 be released ?

**Comment by lance6716** [comment]
> @lance6716 thanks, and when will v2.0.4 be released ?

release date of v2.0.4 is not decided yet, you could join https://slack.tidb.io/invite?team=tidb-community&channel=sig-migrate&ref=github_sig and ask us later

**Comment by reAsOn2010** [comment]
> > @lance6716 thanks, and when will v2.0.4 be released ?
> 
> release date of v2.0.4 is not decided yet, you could join https://slack.tidb.io/invite?team=tidb-community&channel=sig-migrate&ref=github_sig and ask us later

OK, thanks!

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
