### PR TITLE
Quality reinforcement (9): fix unstable test cases

### PR DESCRIPTION
**Pull request by lance6716**
- [x] testElectionSuite.TestElectionEvictLeader [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7989/pipeline/72) https://github.com/pingcap/dm/pull/1412/commits/4d670d9b18f5223e1cbf2a7c26b1b7be2cf33559
  seems "some unit test using etcd [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7989/pipeline/72)" is failed because etcd too slow

  ```
  [2021-01-11T08:54:57.388Z] [2021/01/11 16:53:08.828 +08:00] [WARN] [util.go:163] ["apply request took too long"] [took=1.630559395s] [expected-duration=100ms] [prefix=] [request="header:<ID:14726057132519571993 > txn:<compare:<target:CREATE key:\"unit-test/election-evict-leader/4c5d76f0a5efc205\" create_revision:0 > success:<request_put:<key:\"unit-test/election-evict-leader/4c5d76f0a5efc205\" value_size:40 lease:5502685095664796165 >> failure:<request_range:<key:\"unit-test/election-evict-leader/4c5d76f0a5efc205\" > >>"] [response=size:14] []
  ...
  [2021-01-11T08:54:57.388Z] [2021/01/11 16:53:08.830 +08:00] [INFO] [election.go:292] ["get response from election observe"] [component=election] [key=unit-test/election-evict-leader/4c5d76f0a5efc205] [value="{\"id\":\"member1\",\"addr\":\"127.0.0.1:1234\"}"]
  ```

  putting election key spends more than 1 second, so in the test sleeping 1 second and checking the leader is not enough
- [ ] testSubTask.TestPauseAndResumeSubtask subtask_test.go:365 ~[jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8133/pipeline/)~
   maybe ther's a little chance that the checker just peek when after `setResult` and before `setStage`
- [ ] testSubTask.TestPauseAndResumeSubtask subtask_test.go:394: ~[jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8205/pipeline)~
   maybe ther's a little chance that the checker just peek when after `setCurrUnit` and before `setResult`
- [x] testRelaySuite.TestProcess relay_test.go:663 ~[jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8215/pipeline)~ https://github.com/pingcap/dm/pull/1412/commits/20c08ef3ca37eae6787430e4afecabea9cff7c29
- [ ] testMaster.TestOperateSource server_test.go:1364: ~[jenkins](https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/dm_ghpr_test/runs/8269/nodes/72/steps/410/log/?start=0)~
   lost needed log
- [ ] testEtcdUtilSuite.TestEtcdUtil etcdutil_test.go:201: ~[jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8338/pipeline)~
   lost needed log
- [ ] DM-102 ~[jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8339/pipeline/89)~
   lost needed log
- [ ] ~some unit test [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8369/pipeline)~
- [ ] testReaderSuite.TestParseFileRelaySubDirUpdated reader_test.go:289 ~[jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8495/pipeline/72)~
   lost needed log
- [ ] ha_master, leader evict failed errror [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8507/pipeline/77)
   don't know why 😂 
- [x] only_dml, we check "purging relay log" before flush global checkpoint, so no relay log purged [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8629/pipeline) https://github.com/pingcap/dm/pull/1412/commits/123b1408e7d6c1e47a179748a98f10af262400b3 https://github.com/pingcap/dm/pull/1412/commits/7d748a486d0df4d7832a0e43020abcf8e8755834
   besides, `start purging relay log files` in log didn't output `arg` properly
- [x] testElectionSuite.TestElectionEvictLeader election_test.go:355 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8731/pipeline/) https://github.com/pingcap/dm/pull/1412/commits/8ad3ceb0ebbc1e66fb2fc4e8f69f700efb6340f7
- [ ] DM-143, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8773/pipeline) will be fixed in another PR @gozssky 
- [ ] DM-136, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8788/pipeline) worker1 should DROP the index, but it runs slowly so DROP after worker2 ADD the new index with same name
- [ ] all_mode, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8800/pipeline), https://github.com/pingcap/dm/pull/1412/commits/fcfbc027f071736daf8edb88a0b5000c26036500 (add log)
   failed the check about `[ $relay_log_num -eq 1 ]`, but `echo` shows there's should be only one line
- [x] DM-147 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8811/pipeline) https://github.com/pingcap/dm/pull/1412/commits/1dfcb67f6c3b6cc0cf90df4f0f4b4a45a6e18900
- [x] DM 147 operate-schema set when running [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8826/pipeline) [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8851/pipeline) https://github.com/pingcap/dm/pull/1412/commits/1dfcb67f6c3b6cc0cf90df4f0f4b4a45a6e18900
- [x] testServer.TestWatchSourceBoundEtcdCompact server_test.go:414 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8817/pipeline/72) https://github.com/pingcap/dm/pull/1412/commits/fcfbc027f071736daf8edb88a0b5000c26036500
- [x] DM-DropAddColumn [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8842/pipeline) [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8859/pipeline) https://github.com/pingcap/dm/pull/1412/commits/1dfcb67f6c3b6cc0cf90df4f0f4b4a45a6e18900
- [x] DM-117 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8847/pipeline/89) https://github.com/pingcap/dm/pull/1412/commits/1dfcb67f6c3b6cc0cf90df4f0f4b4a45a6e18900
- [ ] testMaster.TestJoinMember server_test.go:1251 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/dm_ghpr_test/runs/8854/nodes/72/steps/225/log/?start=0)
   seems builtin context timeout
- [x] testForEtcd.TestInfoEtcd info_test.go:188 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8862/pipeline/) https://github.com/pingcap/dm/pull/1412/commits/a3f97b0c62803a212e6709d9e60ebb477c60fd4b

### CODE REVIEW

**Comment by lance6716** [comment]
PTAL @GMHDBJD @lichunzhu @gozssky

**Review by GMHDBJD — APPROVED** [review]
/lgtm

**Pull request merged**
