### PR TITLE
Quality reinforcement (4): fix unstable test cases

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
fix unstable test cases in CI.
- [ ] ha_cases test_kill_master, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6764/pipeline)
  root cause: upstream MySQL doesn't generate binlog? could search `5693` in worker1's log, that's the last event recieved.
- [ ] ha_case test_multi_task_reduce_and_restart_worker, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7059/pipeline)
- [ ] ha_cases [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6815/pipeline)
  root cause:  `Error while dialing dial tcp 127.0.0.1:8262: connect: connection refused`
- [ ] ha_cases [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6822/pipeline/77), [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6889/pipeline), [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7005/pipeline)
- [x] import_goroutine_leak, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6784/pipeline), caused by some "send on closed channel" panic not stable
- [ ] testRelaySuite.TestProcess, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6799/pipeline), [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6800/pipeline/)
- [ ] testPessimist.TestUnlockSourceInterrupt, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6806/pipeline)
- [ ] testMaster.TestOfflineMember: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6814/pipeline), [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6939/pipeline/) what to do if leader forwarding fails?
- [x] ha_master, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6829/pipeline), lance6716
- [x] shardddl3 DM-RemoveLock, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6898/pipeline), [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6925/pipeline), gmhdbjd, 546e203
- [x] load_interrupt, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6900/pipeline), [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6933/pipeline), [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7004/pipeline/82), lance6716 https://github.com/pingcap/dm/pull/1046/commits/75a83c8554245b818d1df8718c2a6af9170dd02b
- [x] testScheduler.TestScheduler, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6912/pipeline), lance6716
- [ ] testPessimist.TestPessimist: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6947/pipeline)
- [x] DATA RACE: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6973/pipeline), csuzhangxc, https://github.com/pingcap/dm/pull/1091/commits/f5dc769f68ab7b1f19886d5fff12a9bc1f6b74f1
    - move `cpuUsageGauge` from `Worker` to `Server`
- [x] DM-063 optimistic: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6975/pipeline/90/), gmhdbjd, 4d0eedf
- [ ] shardddl/optimism [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6992/pipeline)
- [ ] http_apis, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6995/pipeline/78)
- [ ] testScheduler.TestRestartScheduler, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7046/pipeline)
- [ ] DM-CASE-94, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7090/)
- [ ] testForEtcd.TestOperationEtcd, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7093/pipeline/)
- [ ] testElectionSuite.TestElection2After1, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7096/pipeline)

### CODE REVIEW

**Comment by lance6716** [comment]
LGTM

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]

**Comment by csuzhangxc** [comment]
/run-all-tests

`Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again`, 🤔

**Comment by csuzhangxc** [comment]
/run-all-tests

`
[2020-09-30T10:33:31.599Z] sh: line 1:    13 Terminated              JENKINS_SERVER_COOKIE=$jsc 'sh' -xe '/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm@tmp/durable-2e3fb136/script.sh' > '/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm@tmp/durable-2e3fb136/jenkins-log.txt' 2>&1`

**Pull request merged**
