### PR TITLE
test: align with TiDB clustered index behaviour

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
revert some of https://github.com/pingcap/dm/pull/1522

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by GMHDBJD** [comment]
Should we enable `alter-primary-key` in schemaTracker?

**Comment by lance6716** [comment]
> Should we enable `alter-primary-key` in schemaTracker?

I want to set OFF clustered index in another PR, so in future we don't need to change again when update TiDB

**Comment by GMHDBJD** [comment]
> I want to set OFF clustered index in another PR, so in future we don't need to change again when update TiDB

Maybe we should set it the same as downstream?

**Comment by lance6716** [comment]
> > I want to set OFF clustered index in another PR, so in future we don't need to change again when update TiDB
> 
> Maybe we should set it the same as downstream?

downstream may change global variable of clustered index and rebuild the table, at that time schema tracker has no way to know that change. I prefer keep schema tracker maximum compatibility of DDL.

**Comment by GMHDBJD** [comment]
Will a create table stmt `create table tb(id int)` from upstream become `create table tb(id int nonclustered)` in tracker and exec to TiDB if we set `clustered index` OFF

**Pull request merged**
