### PR TITLE
ansible: add & update metric panels for syncer and misc

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
add grafana panels for #772 

### What is changed and how it works?
modify grafana json.

1. multi-selection on source and instance
image

but seems `histogram_quantile`, `rate` can't work on multi-source

2. add panels for worker `opErrCounter`
image

3. change some metrics for worker
- replace filter `$instance` to `$source_id`:
  `dm_worker_task_state`

4. metrics for syncer
- replace filter `$instance` to `$source_id`:
  `dm_syncer_remaining_time`, `dm_syncer_binlog_file`, `dm_syncer_binlog_transform_cost_count`, `dm_syncer_skip_binlog_duration_count`, `dm_syncer_read_binlog_duration_bucket`, `dm_syncer_binlog_transform_cost_bucket`, `dm_syncer_dispatch_binlog_duration_bucket`, `dm_syncer_binlog_event_size_bucket`, `dm_syncer_queue_size`, `dm_syncer_added_jobs_total`, `dm_syncer_finished_jobs_total`, `dm_syncer_add_job_duration_bucket`, `dm_syncer_conflict_detect_duration_bucket`, `dm_syncer_skip_binlog_duration_bucket`, `dm_syncer_unsynced_table_number`, `dm_syncer_shard_lock_resolving`
- keep `$instance`:
  - `dm_syncer_replication_lag`: report by heartbeat, no `source_id` currently
  - `dm_relay_binlog_file{instance="$instance", node="relay"} - ON(instance, job) dm_syncer_binlog_file{instance="$instance", task="$task", node="syncer"}`: relay doesn't have `source_id` currently
  - `dm_syncer_txn_duration_time_bucket`, `dm_syncer_stmt_duration_time_bucket`: used by DBConn in many place (checkpoint, onlineddl, ...), seems it's more appropriate to represent a instance's state 

### Check List 

Tests 

 - Manual test (see panels in broswer)

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by csuzhangxc** [comment]
> add panels for worker opErrCounter

How about re-order panels for opErrCounter? like:

1. before any operate error
2. source bound error
3. start error
4. pause error
5. resume error
6. auto resume error
7. update error
8. stop error

**Comment by lance6716** [comment]
> > add panels for worker opErrCounter
> 
> How about re-order panels for opErrCounter? like:
> 
> 1. before any operate error
> 2. source bound error
> 3. start error
> 4. pause error
> 5. resume error
> 6. auto resume error
> 7. update error
> 8. stop error

visual result updated in description of this PR https://github.com/pingcap/dm/pull/803#issue-449352219

**Pull request merged**
