### PR TITLE
test: check worker is alive before adding source

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
we expected source2 boudn to worker2, but forget to check worker is alive before adding source, so in fact master will bind sources arbitraty

### What is changed and how it works?
wait until worker is alive

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
I'm really not understand what happened in CI https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8741/pipeline/

[worker4.log](https://github.com/pingcap/dm/files/6275569/worker4.log)
[worker4-stdout.log](https://github.com/pingcap/dm/files/6275570/worker4-stdout.log)

seems we started another DM-worker before previous one quit (could found it in stdout), but it exits at line 557 and can't explain we have two duplicated "receive subtask stage change", "read from relay log", "write to relay log" which at line 578, 614, 684 in log.

worker process 1:

```
5: Welcome to dm-worker
13: receive relay source
27: relay enabled *
34: started underlying reader
59: receive source bound
61: starting to handle mysql source
85: handling subtask enabled
138: observeSubtaskStage will quit now
160: relay unit closed
167: exit
```

worker process 2:

```
168: Welcome to dm-worker
175: worker has been assigned relay before keepalive
188: relay enabled *
194: started underlying reader
217: relay unit closed
221: got signal to exit (but not exit quickly)
232: receive source bound
277: receive relay source
302: already enabled relay
348: starting to handle mysql source
370: handling subtask enabled
372: receive source bound
395: relay enabled *
414: started underlying reader
554: already enabled handling subtasks
557: exit
```

worker process 3:

```
* 224: Welcome to dm-worker
* 229: worker has been assigned relay before keepalive
* 235: receive relay source
* 245: relay enabled *
* 247: worker has been assigned source before keepalive
* 252: started underlying reader
* 255: starting to handle mysql source
* 297: handling subtask enabled
* 299: started to handle mysql source
* 483: observeSubtaskStage will quit now
* 491: relay unit closed
* 498: exit
```

worker process 4:

```
- 499: Welcome to dm-worker
- 504: worker has been assigned relay before keepalive
- 519: relay enabled *
- 521: worker has been assigned source before keepalive
- 526: started underlying reader
- 529: starting to handle mysql source
- 551: receive relay source 
- 569: handling subtask enabled
- 571: started to handle mysql source, before it should exist 521
- 573: already enabled relay
- 578: duplicate "receive subtask stage change"
- 614, 616: duplicate read from relay
- 684, 686: duplicate relay write, starting from LogPos 784
```

**Review by GMHDBJD — APPROVED** [review]
/lgtm

**Pull request merged**
