### PR TITLE
*: clear some useless code (#1020)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1020 to release-2.0

---

### What problem does this PR solve? 

- clear some useless code, especially for:
    - mydumper
    - old implement of shard DDL

- NOTE: some code may be cleared later but didn't in this PR:
    - duplicate or similar code
    - code to un-supported features

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by csuzhangxc** [comment]
/run-all-tests

some CI problems like `Operation: [get]  for kind: [Pod]  with name: [test-681e0d78-8b3d-44fd-9083-13f9d11042d1-k0f9w-vpzw5]  in namespace: [jenkins-ci]  failed.`.

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
