### PR TITLE
ansible: update dm_version to v2.0.0-rc.2

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

- update `dm_ansible` for DM-ansible to `v2.0.0-rc.2`.

### Check List 

Tests 

 - No code

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
LGTM

**Comment by csuzhangxc** [comment]
/run-all-tests

[`bash: line 1:   397 Killed `](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6472/pipeline/71)

**Pull request merged**
