### PR TITLE
master: replace wrong usage of utils.Decrypt

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
`start-task --remove-meta` routine will call `utils.Decrypt` which is not suitable for plain password

### What is changed and how it works?
replace to `utils.DecryptOrPlaintext`

### Check List 

Tests 

 - Manual test (I guess no problem, will test **after** merge in Aurora migration)

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
PTAL @csuzhangxc @GMHDBJD

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
passed Manual test

**Pull request merged**
