### PR TITLE
test: update check text to latest tidb

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
after https://github.com/pingcap/tidb/issues/20446, check of `SHOW CREATE TABLE` should alter some text

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by lance6716** [comment]
/run-all-tests

quality improvement (6) have fixed this fail

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
required CI passed

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
