### PR TITLE
ci: try fix chaos mesh

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 
截屏2021-06-03 上午8 27 28

something wrong with the latest chaos-mesh， try use v1.0.0

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by GMHDBJD** [comment]
I think we better figure out why `scheduler` removed in the new version of chaos-mesh and update the config file rather than downgrade it.

**Comment by Ehco1996** [comment]
> I think we better figure out why `scheduler` removed in the new version of chaos-mesh and update the config file rather than downgrade it.

i found this: https://github.com/chaos-mesh/chaos-mesh/discussions/1520, seems `scheduler` became a new `crd` in leatest version, if we want to use this, we need update our chaos tesat yaml.

given there is lot's of PR pending by this `chaos-mesh` job, lock version can be  a quick fix?

**Review by lance6716 — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
