### PR TITLE
syncer, relay: support incremental task with gtid specified only

### LINKED ISSUE #1391: can't start an incremental task with GTID specified only when relay enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

task.yaml
```yaml
task-mode: incremental
...
    meta:
      binlog-gtid: '09bec856-ba95-11ea-850a-58f2b4af5188:15-16'
```

2. What did you expect to see?

start-task success

3. What did you see instead?

```
            "msg": "[code=38032:class=dm-master:scope=internal:level=high], Message: some error occurs in dm-worker: ErrCode:22002 ErrClass:\"binlog-op\" ErrScope:\"internal\" ErrLevel:\"high\" Message:\"fail to initial unit Sync of subtask test : binlog filename  not valid\" , Workaround: Please execute `query-status` to check status.",
```

caused by empty binlog filename
https://github.com/pingcap/dm/blob/2ecaa73a45174fb71c5f6c336da00633b618a109/pkg/streamer/hub.go#L70-L77

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        2.0.1
        ```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1391 

### What is changed and how it works?
don't update active relay log (only used for relay log purging?) when there's no binlog name which may because user only specifiy gtid only. Active relay log will be updated at a XID or DDL event with valid binlog name afterwards.

### Check List 

Tests 

 - Integration test
 
Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
PTAL @3pointer @amyangfei

**Review by 3pointer — APPROVED** [review]
LGTM

**Pull request merged**
