### PR TITLE
dmctl: optimize query-status info

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
Some users don't know how to `query-status` after the info is simplified.

### What is changed and how it works?
Add more info for `query-status` in dmctl.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### CODE REVIEW

**Comment by lichunzhu** [comment]
@WangXiangUSTC @csuzhangxc PTAL

**Comment by WangXiangUSTC** [comment]
LGTM

**Pull request merged**
