### PR TITLE
Quality reinforcement: fix unstable test cases

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
fix unstable test cases in CI.

- [x] table structure check, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6250/pipeline/), gmhdbjd, [#386](https://github.com/pingcap/tidb-tools/pull/386)
- [x] shardddl DM-CASE-022, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6250/pipeline), gmhdbjd, ca4fce6
- [x] ha_master, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6263/pipeline), gmhdbjd, cd805fc
- [x] syncer data race, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6262/pipeline/), lance6716, #925 
- [ ] testScheduler.TestScheduler, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6272/pipeline/70)
- [x] testServer.TestTaskAutoResume, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6268/pipeline/70), lance6716, #933
- [x] testSyncerSuite.TestRun, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6268/pipeline/68), gmhdbjd, 6f79d1f
- [x] shardddl3, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6283/pipeline), gmhdbjd, #939 
- [x] shardddl1, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6108/pipeline/88/), gmhdbjd, ca4fce6
- [x] testReaderSuite.TestStartSync, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6369/pipeline), gmhdbjd, 53dd296

### What is changed and how it works?
- /run-all-tests to find unstable cases.
- push commit in this pr to fix the cases.

### CODE REVIEW

**Comment by lance6716** [comment]
mysterious fail: in `ha_cases`

```
[2020-08-24T04:23:10.484Z] {
[2020-08-24T04:23:10.484Z]     "result": false,
[2020-08-24T04:23:10.484Z]     "msg": "[code=26005:class=dm-master:scope=internal:level=medium], Message: fail to check synchronization configuration with type: check was failed, please see detail
[2020-08-24T04:23:10.484Z]     	detail: {
[2020-08-24T04:23:10.484Z] 		"results": [
[2020-08-24T04:23:10.484Z] 			{
[2020-08-24T04:23:10.484Z] 				"id": 13,
[2020-08-24T04:23:10.484Z] 				"name": "table structure compatibility check",
[2020-08-24T04:23:10.484Z] 				"desc": "check compatibility of table structure",
[2020-08-24T04:23:10.484Z] 				"state": "fail",
[2020-08-24T04:23:10.484Z] 				"errorMsg": "Error 1146: Table 'ha_test.tb' doesn't exist\n",
[2020-08-24T04:23:10.484Z] 				"instruction": "",
[2020-08-24T04:23:10.484Z] 				"extra": "address of db instance - 127.0.0.1:3307"
[2020-08-24T04:23:10.484Z] 			},
[2020-08-24T04:23:10.484Z] 			{
[2020-08-24T04:23:10.484Z] 				"id": 6,
[2020-08-24T04:23:10.484Z] 				"name": "table structure compatibility check",
[2020-08-24T04:23:10.484Z] 				"desc": "check compatibility of table structure",
[2020-08-24T04:23:10.484Z] 				"state": "fail",
[2020-08-24T04:23:10.484Z] 				"errorMsg": "Error 1146: Table 'ha_test.ta' doesn't exist\n",
[2020-08-24T04:23:10.484Z] 				"instruction": "",
[2020-08-24T04:23:10.484Z] 				"extra": "address of db instance - 127.0.0.1:3306"
[2020-08-24T04:23:10.484Z] 			}
[2020-08-24T04:23:10.484Z] 		],
[2020-08-24T04:23:10.484Z] 		"summary": {
[2020-08-24T04:23:10.484Z] 			"passed": false,
[2020-08-24T04:23:10.484Z] 			"total": 14,
[2020-08-24T04:23:10.484Z] 			"successful": 12,
[2020-08-24T04:23:10.484Z] 			"failed": 2,
[2020-08-24T04:23:10.484Z] 			"warning": 0
[2020-08-24T04:23:10.484Z] 		}
[2020-08-24T04:23:10.484Z] 	}",
[2020-08-24T04:23:10.484Z]     "sources": [
[2020-08-24T04:23:10.484Z]     ]
[2020-08-24T04:23:10.484Z] }
```

**Comment by lance6716** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6258/pipeline

```
[Mon Aug 24 19:23:53 CST 2020] <<<<<< start DM-022  >>>>>>

[2020-08-24T11:23:53.345Z] dmctl test cmd: "start-task /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/tests/shardddl1/conf/single-source-no-routes.yaml --remove-meta"

[2020-08-24T11:23:55.863Z] ERROR 1049 (42000) at line 1: Unknown database 'shardddl1'
```

**Comment by lance6716** [comment]
found in CI's print-all-log https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6262/pipeline/

```
[2020-08-24T12:30:18.323Z] WARNING: DATA RACE
[2020-08-24T12:30:18.323Z] Read at 0x00c003100b58 by goroutine 137:
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/syncer.(*RemoteCheckPoint).FlushedGlobalPoint()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/checkpoint.go:535 +0xbc
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/syncer.(*Syncer).Status()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/status.go:43 +0x188
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/worker.(*Worker).Status()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/status.go:103 +0x7ce
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/worker.(*Worker).QueryStatus()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/worker.go:307 +0x1bb
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/worker.(*Server).QueryStatus()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/server.go:524 +0x587
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/pb._Worker_QueryStatus_Handler()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/pb/dmworker.pb.go:3556 +0x37c
[2020-08-24T12:30:18.323Z]   google.golang.org/grpc.(*Server).processUnaryRPC()
[2020-08-24T12:30:18.323Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x983
[2020-08-24T12:30:18.323Z]   google.golang.org/grpc.(*Server).handleStream()
[2020-08-24T12:30:18.323Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0x1343
[2020-08-24T12:30:18.323Z]   google.golang.org/grpc.(*Server).serveStreams.func1.1()
[2020-08-24T12:30:18.323Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xc8
[2020-08-24T12:30:18.323Z] 
[2020-08-24T12:30:18.323Z] Previous write at 0x00c003100b58 by goroutine 268:
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/syncer.(*RemoteCheckPoint).LoadMeta()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/checkpoint.go:760 +0x971
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/syncer.(*Syncer).Run()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/syncer.go:1088 +0x6d97
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/syncer.(*Syncer).Process()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/syncer.go:533 +0x5d7
[2020-08-24T12:30:18.323Z] 
[2020-08-24T12:30:18.323Z] Goroutine 137 (running) created at:
[2020-08-24T12:30:18.323Z]   google.golang.org/grpc.(*Server).serveStreams.func1()
[2020-08-24T12:30:18.323Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xb8
[2020-08-24T12:30:18.323Z]   google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
[2020-08-24T12:30:18.323Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/internal/transport/http2_server.go:447 +0x16a6
[2020-08-24T12:30:18.323Z]   google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
[2020-08-24T12:30:18.323Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/internal/transport/http2_server.go:488 +0x459
[2020-08-24T12:30:18.323Z]   google.golang.org/grpc.(*Server).serveStreams()
[2020-08-24T12:30:18.323Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:718 +0x19a
[2020-08-24T12:30:18.323Z]   google.golang.org/grpc.(*Server).handleRawConn.func1()
[2020-08-24T12:30:18.323Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:679 +0x4c
[2020-08-24T12:30:18.323Z] 
[2020-08-24T12:30:18.323Z] Goroutine 268 (running) created at:
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/worker.(*SubTask).run()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/subtask.go:214 +0x5d7
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/worker.(*SubTask).fetchResult()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/subtask.go:290 +0x115b
[2020-08-24T12:30:18.323Z] ==================
[2020-08-24T12:30:18.323Z] ==================
[2020-08-24T12:30:18.323Z] WARNING: DATA RACE
[2020-08-24T12:30:18.323Z] Read at 0x00c006442200 by goroutine 137:
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/syncer.(*binlogPoint).FlushedMySQLLocation()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/checkpoint.go:146 +0xdd
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/syncer.(*RemoteCheckPoint).FlushedGlobalPoint()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/checkpoint.go:535 +0xd1
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/syncer.(*Syncer).Status()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/status.go:43 +0x188
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/worker.(*Worker).Status()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/status.go:103 +0x7ce
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/worker.(*Worker).QueryStatus()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/worker.go:307 +0x1bb
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/worker.(*Server).QueryStatus()
[2020-08-24T12:30:18.323Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/server.go:524 +0x587
[2020-08-24T12:30:18.323Z]   github.com/pingcap/dm/dm/pb._Worker_QueryStatus_Handler()
[2020-08-24T12:30:18.324Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/pb/dmworker.pb.go:3556 +0x37c
[2020-08-24T12:30:18.324Z]   google.golang.org/grpc.(*Server).processUnaryRPC()
[2020-08-24T12:30:18.324Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x983
[2020-08-24T12:30:18.324Z]   google.golang.org/grpc.(*Server).handleStream()
[2020-08-24T12:30:18.324Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0x1343
[2020-08-24T12:30:18.324Z]   google.golang.org/grpc.(*Server).serveStreams.func1.1()
[2020-08-24T12:30:18.324Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xc8
[2020-08-24T12:30:18.324Z] 
[2020-08-24T12:30:18.324Z] Previous write at 0x00c006442200 by goroutine 268:
[2020-08-24T12:30:18.324Z]   github.com/pingcap/dm/syncer.(*RemoteCheckPoint).LoadMeta()
[2020-08-24T12:30:18.324Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/checkpoint.go:76 +0x7e2
[2020-08-24T12:30:18.324Z]   github.com/pingcap/dm/syncer.(*Syncer).Run()
[2020-08-24T12:30:18.324Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/syncer.go:1088 +0x6d97
[2020-08-24T12:30:18.324Z]   github.com/pingcap/dm/syncer.(*Syncer).Process()
[2020-08-24T12:30:18.324Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/syncer.go:533 +0x5d7
[2020-08-24T12:30:18.324Z] 
[2020-08-24T12:30:18.324Z] Goroutine 137 (running) created at:
[2020-08-24T12:30:18.324Z]   google.golang.org/grpc.(*Server).serveStreams.func1()
[2020-08-24T12:30:18.324Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xb8
[2020-08-24T12:30:18.324Z]   google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
[2020-08-24T12:30:18.324Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/internal/transport/http2_server.go:447 +0x16a6
[2020-08-24T12:30:18.324Z]   google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
[2020-08-24T12:30:18.324Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/internal/transport/http2_server.go:488 +0x459
[2020-08-24T12:30:18.324Z]   google.golang.org/grpc.(*Server).serveStreams()
[2020-08-24T12:30:18.324Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:718 +0x19a
[2020-08-24T12:30:18.324Z]   google.golang.org/grpc.(*Server).handleRawConn.func1()
[2020-08-24T12:30:18.324Z]       /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:679 +0x4c
[2020-08-24T12:30:18.324Z] 
[2020-08-24T12:30:18.324Z] Goroutine 268 (running) created at:
[2020-08-24T12:30:18.324Z]   github.com/pingcap/dm/dm/worker.(*SubTask).run()
[2020-08-24T12:30:18.324Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/subtask.go:214 +0x5d7
[2020-08-24T12:30:18.324Z]   github.com/pingcap/dm/dm/worker.(*SubTask).fetchResult()
[2020-08-24T12:30:18.324Z]       /home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/dm/worker/subtask.go:290 +0x115b
[2020-08-24T12:30:18.324Z] ==================
```

**Comment by lance6716** [comment]
progress save:

failure of `testServer.TestTaskAutoResum` is caused by auto-resume too fast, before the "pause" check task resumed twice and enter "forever running" stage

**Comment by lance6716** [comment]
progress declare:
in (s *testSyncerSuite) TestRun:

```
{false [ErrCode:44007 ErrClass:"schema-tracker" ErrScope:"downstream" ErrLevel:"medium" Message:"startLocation: [position: (, 1713), gtid-set: ], endLocation: [position: (, 1755), gtid-set: ]: cannot fetch downstream table schema of `test_1`.`t_2` to initialize upstream schema `test_1`.`t_1` in schema tracker" RawCause:"all expectations were already fulfilled, call to Query 'SHOW CREATE TABLE `test_1`.`t_2`' with args [] was not expected" ] []}
```

**Comment by lance6716** [comment]
seems we need to add more workload 😂

**Comment by lance6716** [comment]
/run-all-tests

test jenkins could `println "branch=${env.BRANCH_NAME}"`

**Comment by lance6716** [comment]
/run-all-tests

I have saved pipeline a minute ago

**Comment by lance6716** [comment]
/run-all-tests

try fix container image

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
LGTM

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
sequence_sharding_optimistic: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6407/pipeline)

**Comment by csuzhangxc** [comment]
ha: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6432/pipeline)

**Pull request merged**
