### PR TITLE
tests: add unit test coverage report

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 
we have not unit test coverage report now

### What is changed and how it works?
upload unit test coverage to codecov

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by amyangfei** [comment]
PTAL @GregoryIan @csuzhangxc

**Comment by amyangfei** [comment]
> LGTM but remember to enable the CodeCov GitHub integrations for the checks.

yep, already added. https://codecov.io/gh/pingcap/dm/branches

**Comment by kennytm** [comment]
No I mean this:

Screenshot 2019-05-12 at 21 02 34-fs8

This needs the admin of the `pingcap` organization to enable it.

Notice that this PR only has 3 successful checks (Coveralls, Jenkins, CLA) instead of 4 (+ CodeCov).

**Comment by amyangfei** [comment]
> No I mean this:
> 
> Screenshot 2019-05-12 at 21 02 34-fs8
> 
> This needs the admin of the `pingcap` organization to enable it.
> 
> Notice that this PR only has 3 successful checks (Coveralls, Jenkins, CLA) instead of 4 (+ CodeCov).

I see, PTAL @GregoryIan

**Comment by kennytm** [comment]
FYI, the codecov integration has been enabled.

**Pull request merged**
