### PR TITLE
test: bring `run-compatibility-test` back (#1128)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1128 to release-2.0

---

### What problem does this PR solve? 
reveal bug that break upgrading.

### What is changed and how it works?

compatibility test will run a 1-master-2-worker task, try kill-and-replace master, worker, another worker to check task running well.

default behaviour:
- old master and worker are `v2.0.0-rc`
- only run `compatibility`

apart from https://github.com/pingcap/dm/pull/262, use `/run-compatibility-test break_compatibility=true` to bypass compatibility test if PR require break compatibility

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by lance6716** [comment]
not sure 2.0 will need this, I suppose only develop branch need check compatibility

**Comment by csuzhangxc** [comment]
> not sure 2.0 will need this, I suppose only develop branch need check compatibility

we may open PR to release-2.0 branch someday if we are developing v3.0 on the master branch.

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
