### PR TITLE
*: update and fix CI for release-1.0

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

- update and fix CI for release-1.0

### What is changed and how it works?

- update dep to match the current master branch (https://github.com/pingcap/dm/commit/b58e6030a921d44435719f14c4653ad861018189)
- update code to be compatible with dep
- update jenkins CI pipeline

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by csuzhangxc** [comment]
/run-all-tests

debug CI pipeline env vars

**Comment by lance6716** [comment]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
