### PR TITLE
tests: split bing test case

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 

#1727 

### What is changed and how it works?

split big test case so they can run in ci Concurrently
Details:

1.  find all test running longger than 6 min
    * ha_cases
    * ha_cases2
    * handle_error
    * sharddl1
    * sharddl2
    * sharddl3
    * sharddl4
    * others

2. split those tests to another test scripts
    * ha_cases -> ha_cases ha_cases_1 ha_cases_2
    * ha_cases2 -> ha_cases3 ha_cases3_1
    * handle_error -> handle_error handle_error_2 handle_error_3
    * sharddl1 -> sharddl1 sharddl1_1
    * sharddl2 -> sharddl2 sharddl1_1
    * sharddl2 -> sharddl2 sharddl1_1
    * sharddl2 -> sharddl2 sharddl1_1
    * others -> remove some case from `others_integration.txt` and add them to new ci job

the new  [tests directory structure](https://github.com/Ehco1996/dm/tree/split-shard-test-cases/tests) may help to understand tests changes better

**result:**
after split tests, ci running time finally decrease to 13m [jenkins](https://ci.pingcap.net/blue/organizations/jenkins/dm_ghpr_new_test/detail/dm_ghpr_new_test/395/pipeline/159)

also need to change jenkins pipline file in  https://github.com/PingCAP-QE/ci/pull/231 after this pr merged

### Check List 

Tests 

 - Integration test
 - No code

Code changes

- None

Side effects

-None

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by Ehco1996** [comment]
after split tests, ci running time finally decrease to 13m [jenkins](https://ci.pingcap.net/blue/organizations/jenkins/dm_ghpr_new_test/detail/dm_ghpr_new_test/395/pipeline/159)

**Comment by Ehco1996** [comment]
we should merge this before update ci [pr](https://github.com/PingCAP-QE/ci/pull/231)

**Comment by lance6716** [comment]
too many changes 😂 could you write steps about your actions of this PR?

**Comment by Ehco1996** [comment]
> too many changes 😂 could you write steps about your actions of this PR?

@lance6716  added in desription

**Comment by lance6716** [comment]
what's ha_cases3 in "find all test running longger than 6 min", we don't have this folder 🤔 does it come from a previous split?

**Comment by Ehco1996** [comment]
> what's ha_cases3 in "find all test running longger than 6 min", we don't have this folder 🤔 does it come from a previous split?

yes, `ha_cases2` split to `ha_cases3` and  `ha_cases3_1`

**Review by lance6716 — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
