### PR TITLE
dmctl: disable unsupported command

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
#856 #897 

### What is changed and how it works?
- disable currently not supported command in dmctl
- do not auto-resume for DMLColumnNotMatch error

### Check List 

Tests 
 - Integration test

### CODE REVIEW

**Comment by lance6716** [comment]
Could DMLColumnNotMatch be resolved by some downstream operations? If so, we'd better leave DMLColumnNotMatch auto-resumable

**Comment by csuzhangxc** [comment]
> Could DMLColumnNotMatch be resolved by some downstream operations? If so, we'd better leave DMLColumnNotMatch auto-resumable

This usually means that something unexpected happened. and in some supported cases, the user still needs to use `operate-schema` to fix it.

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
LGTM

**Review by lance6716 — APPROVED** [review]

**Comment by csuzhangxc** [comment]
@GMHDBJD `needs-update-docs`.

**Pull request merged**
