### PR TITLE
dep: update go-mysql to introduce DECIMAL optimization

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close https://github.com/pingcap/dm/issues/1826

### Check List 

Tests 

 - benchmark 1
   using sysbench, but change the `k` column to decimal (40, 16). start a v5.0.1 TiDB in same host with DM (in short of VM 😢)
   without this PR: dm-worker CPU ~250%, TiDB CPS 18.0k
   with this PR: dm-worker CPU ~250%, TiDB CPS 19.5k
- benchmark 2
   using sysbench like above, start a v4.0.13 TiDB in another host. task concurrency is 96.
   without this PR: dm-worker CPU mean 148%, 147%, TiDB CPS 10.0k
   with this PR: dm-worker CPU mean 143%, 146%, TiDB CPS 10.0k
   the decodeDecimal only occupied 3.5% CPU, so the optimization takes a little effects.

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/hold

waiting benchmark

**Review by glorv — APPROVED** [review]

**Pull request merged**
