### PR TITLE
fix: don't forbid DM-master leader startup for unexpected DDL locks (#1193)

### LINKED ISSUE #1185: dm-master can't start if optimistic shard DDL conflicts exists in etcd data
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

    in an infinite loop:
    - election become the leader
    - try start optimist
    - fail to start optimist because `there will be conflicts"
    - retire from the leader

[dm-master-can-not-setup.log](https://github.com/pingcap/dm/files/5401088/dm-master-can-not-setup.log)

3. What did you see instead?

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        master branch at least until https://github.com/pingcap/dm/commit/925c59b6a619dd7cb9ce60a986bbf53c002c7550
        ```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1193 to release-2.0

---

### What problem does this PR solve? 

fix #1185 

### What is changed and how it works?

- don't forbid DM-master leader startup for unexpected DDL locks

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by lance6716** [comment]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Comment by csuzhangxc** [comment]
/run-all-tests

`hudson.plugins.git.GitException: Failed to fetch from git@github.com:pingcap/dm.git`

**Pull request merged**
