### PR TITLE
test: support verify CI

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 
as title

### What is changed and how it works?
can preview this CI in [here](https://ci.pingcap.net/blue/organizations/jenkins/dm-verify-ci-test/detail/dm-verify-ci-test/7/pipeline/21)

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
lgtm, why we need these new tools?

**Comment by Ehco1996** [comment]
> lgtm, why we need these new tools?

those tools can make jenkins preview error when test failed 
image

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
