### PR TITLE
*: refine dashboard

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

refine the dashboard

### What is changed and how it works?

- only show instances for the selected task
- add the description for metrics
- add an overview monitoring for the task
	- see screenshot below
- add a board for the status of the instance
	- see screenshot below

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
 	- run some tasks
	- observe the dashboard

Related changes

 - Need to update the documentation
 - Need to update the `dm/dm-ansible`

verview monitoring for the task

board for the status of the instance

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@GregoryIan @amyangfei PTAL

**Comment by GregoryIan** [comment]
should we display instance name in panel for `an overview monitoring for the task`?

**Comment by GregoryIan** [comment]
LGTM

**Comment by csuzhangxc** [comment]
> should we display instance name in panel for `an overview monitoring for the task` and `the status of the instance`?

you can see the instance name  drop-down list of templating in the upper-left corner.

**Pull request merged**
