### PR TITLE
error_message: remove stack error for flag

### LINKED ISSUE #818: don't print stack for unknown flag
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
```
➜  bin git:(master) ✗ ./dm-master -v
flag provided but not defined: -v
Usage of dm-master:
  -L string
        log level: debug, info, warn, error, fatal (default "info")
  -V    prints version and exit
  -advertise-addr string
        advertise address for client traffic (default "${master-addr}")
  -advertise-peer-urls string
        advertise URLs for peer traffic (default "${peer-urls}")
  -config string
        path to config file
  -data-dir string
        path to the data directory (default "default.${name}")
  -initial-cluster string
        initial cluster configuration for bootstrapping, e.g. dm-master=http://127.0.0.1:8291
  -join string
        join to an existing cluster (usage: cluster's "${master-addr}" list, e.g. "127.0.0.1:8261,127.0.0.1:18261"
  -log-file string
        log file path
  -log-format string
        the format of the log, "text" or "json" (default "text")
  -master-addr string
        master API server and status addr
  -name string
        human-readable name for this DM-master member
  -peer-urls string
        URLs for peer traffic (default "http://127.0.0.1:8291")
  -print-sample-config
        print sample config file of dm-worker
parse cmd flags err [code=38010:class=dm-master:scope=internal:level=medium], Message: parse config flag set, RawCause: flag provided but not defined: -v
github.com/pingcap/dm/pkg/terror.(*Error).Delegate
        /Users/huangjiahao/go/src/github.com/pingcap/dm/pkg/terror/terror.go:305
github.com/pingcap/dm/dm/master.(*Config).Parse
        /Users/huangjiahao/go/src/github.com/pingcap/dm/dm/master/config.go:149
main.main
        /Users/huangjiahao/go/src/github.com/pingcap/dm/cmd/dm-master/main.go:36
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
➜  bin git:(master) ✗ ./dm-master -V
Release Version: v2.0.0-beta.2-30-g548c8660
Git Commit Hash: 548c866069d146903eb0cb69ea00c971201a19bb
Git Branch: master
UTC Build Time: 2020-07-23 05:16:24
Go Version: go version go1.14 darwin/amd64
```
2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
548c866069d146903eb0cb69ea00c971201a19bb        ```

    - Upstream MySQL/MariaDB server version:

        ```
        (paste upstream MySQL/MariaDB server version here)
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        (leave DM-Ansible or manually here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
close #818 

### What is changed and how it works?
change ErrorStack to terror.Message

Tests 
 - Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Comment by lance6716** [comment]
LGTM

maybe push something to refresh Hound CI?

**Comment by csuzhangxc** [comment]
> maybe push something to refresh Hound CI?

Hound CI is not _Required_, it's OK for now.

**Comment by csuzhangxc** [comment]
@GMHDBJD should we need to cherry-pick _release-1.0_?

**Pull request merged**
