### PR TITLE
dep: update parser and other dependencies to latest

### LINKED ISSUE #1227: Track parser support multiple table rename
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://github.com/pingcap/parser/pull/1021 , now for a single table rename, we don't have four tableName

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1227 

### What is changed and how it works?
update parser (and other dependencies) to latest.

change uuid to google/uuid

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
waiting https://github.com/chaos-mesh/go-sqlsmith/pull/9 (not sure why go.mod in go-sqlsmith doesn't take effect)

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
```
[2020-11-20T07:07:52.969Z] FAIL: ddl_test.go:75: testSyncerSuite.TestCommentQuote

[2020-11-20T07:07:52.969Z] 

[2020-11-20T07:07:52.969Z] ddl_test.go:91:

[2020-11-20T07:07:52.969Z]     c.Assert(sqls[0], Equals, expectedSQL)

[2020-11-20T07:07:52.969Z] ... obtained string = "ALTER TABLE `schemadb`.`ep_edu_course_message_auto_reply` MODIFY COLUMN `answer` JSON COMMENT _UTF8MB4'回复的内容-格式为list，有两个字段：\"answerType\"：//''发送客服消息类型：1-文本消息，2-图片，3-图文链接''；  answer：回复内容'"

[2020-11-20T07:07:52.969Z] ... expected string = "ALTER TABLE `schemadb`.`ep_edu_course_message_auto_reply` MODIFY COLUMN `answer` JSON COMMENT '回复的内容-格式为list，有两个字段：\"answerType\"：//''发送客服消息类型：1-文本消息，2-图片，3-图文链接''；  answer：回复内容'"
```

seems parser has bug when restore

**Comment by lance6716** [comment]
waiting https://github.com/pingcap/parser/pull/1012

**Comment by lance6716** [comment]
add `sleep 5` is not enough for test sequence_sharding, because test failed at missing column `e`, and last log of worker `e` just get synced

```
[2020-11-23T11:00:40.299Z] [2020/11/23 19:00:38.634 +08:00] [INFO] [syncer.go:1948] ["try to sync table in shard group"] [task=sequence_sharding] [unit="binlog replication"] [event=query] [source=`sharding_seq`.`t4`] [ddls="[\"ALTER TABLE `sharding_target2`.`t_target` ADD COLUMN `e` INT\",\"ALTER TABLE `sharding_target2`.`t_target` ADD INDEX `e`(`e`)\"]"] ["raw statement"="alter table t4 add column e int, add index e(e)"] [in-sharding=true] ["start location"="position: (test-4124ef4b-9f90-45bc-b366-5ef9d3088079-mzs42-pt8s2-bin.000001, 8225), gtid-set: "] [is-synced=true] [unsynced=0]
```

so does test DM_080

**Comment by lance6716** [comment]
CI will pass soon, ping @GMHDBJD

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
/run-all-tests

DATA RACE is recorded

**Comment by lance6716** [comment]
PTAL @GMHDBJD

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
