### PR TITLE
dep: update pingcap/pd to tikv/pd

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
update pingcap/pd to tikv/pd since PD’s migration to TiKV organization

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by GMHDBJD** [comment]
You can also update tidb-tool, tidb, and dumpling because they also update pd.

**Comment by lance6716** [comment]
> You can also update tidb-tool, tidb, and dumpling because they also update pd.

will update dumpling now. other repo has been updated

**Comment by GMHDBJD** [comment]
> will update dumpling now. other repo has been updated

I mean update dm's go.mod 😂

**Comment by lance6716** [comment]
now we still have these dependency path for old pd:

```
github.com/pingcap/pd/v4@v4.0.0-rc.2.0.20200730093003-dc8c75cf7ca0
github.com/ngaut/unistore@v0.0.0-20200806113332-5b9f73333a19
github.com/pingcap/tidb@v1.1.0-beta.0.20200810064414-d81150394f9d
github.com/pingcap/br@v0.0.0-20200820083933-d9d6207c0aa7
github.com/pingcap/tidb@v1.1.0-beta.0.20200825092018-e52cb3714e24
```

```
github.com/pingcap/pd/v4@v4.0.0-rc.2.0.20200715061836-4971825321cf
github.com/pingcap/tidb@v1.1.0-beta.0.20200803035726-41c23700d8d1
github.com/ngaut/unistore@v0.0.0-20200803051709-607d96233b1d
github.com/pingcap/br@v0.0.0-20200803052654-e6f63fc1807a
github.com/pingcap/tidb@v1.1.0-beta.0.20200805053026-cd3e5ed82671
github.com/pingcap/br@v0.0.0-20200805121136-181c081ba6ac
github.com/pingcap/tidb@v1.1.0-beta.0.20200806060043-574540aa06ba
github.com/ngaut/unistore@v0.0.0-20200806113332-5b9f73333a19
github.com/pingcap/tidb@v1.1.0-beta.0.20200810064414-d81150394f9d
github.com/pingcap/br@v0.0.0-20200820083933-d9d6207c0aa7
github.com/pingcap/tidb@v1.1.0-beta.0.20200825092018-e52cb3714e24
```

```
github.com/pingcap/pd/v4@v4.0.0-rc.2.0.20200520083007-2c251bd8f181
github.com/ngaut/unistore@v0.0.0-20200603091253-e0b717679796
github.com/pingcap/tidb@v1.1.0-beta.0.20200603101356-552e7709de0d
github.com/ngaut/unistore@v0.0.0-20200604043635-5004cdad650f
github.com/pingcap/tidb@v1.1.0-beta.0.20200604055950-efc1c154d098
github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154
github.com/pingcap/tidb@v1.1.0-beta.0.20200610060912-f12cdc42010f
github.com/pingcap/br@v0.0.0-20200617120402-56e151ad8b67
github.com/pingcap/tidb@v1.1.0-beta.0.20200721005019-f5c6e59f0daf
github.com/pingcap/br@v0.0.0-20200727092753-a475692725db
github.com/pingcap/tidb@v1.1.0-beta.0.20200803035726-41c23700d8d1
github.com/ngaut/unistore@v0.0.0-20200803051709-607d96233b1d
github.com/pingcap/br@v0.0.0-20200803052654-e6f63fc1807a
github.com/pingcap/tidb@v1.1.0-beta.0.20200805053026-cd3e5ed82671
github.com/pingcap/br@v0.0.0-20200805121136-181c081ba6ac
github.com/pingcap/tidb@v1.1.0-beta.0.20200806060043-574540aa06ba
github.com/ngaut/unistore@v0.0.0-20200806113332-5b9f73333a19
github.com/pingcap/tidb@v1.1.0-beta.0.20200810064414-d81150394f9d
github.com/pingcap/br@v0.0.0-20200820083933-d9d6207c0aa7
github.com/pingcap/tidb@v1.1.0-beta.0.20200825092018-e52cb3714e24
```

```
github.com/pingcap/pd/v4@v4.0.0-rc.2.0.20200714122454-1a64f969cb3c
github.com/pingcap/tidb@v1.1.0-beta.0.20200721005019-f5c6e59f0daf
github.com/pingcap/br@v0.0.0-20200727092753-a475692725db
github.com/pingcap/tidb@v1.1.0-beta.0.20200803035726-41c23700d8d1
github.com/ngaut/unistore@v0.0.0-20200803051709-607d96233b1d
github.com/pingcap/br@v0.0.0-20200803052654-e6f63fc1807a
github.com/pingcap/tidb@v1.1.0-beta.0.20200805053026-cd3e5ed82671
github.com/pingcap/br@v0.0.0-20200805121136-181c081ba6ac
github.com/pingcap/tidb@v1.1.0-beta.0.20200806060043-574540aa06ba
github.com/ngaut/unistore@v0.0.0-20200806113332-5b9f73333a19
github.com/pingcap/tidb@v1.1.0-beta.0.20200810064414-d81150394f9d
github.com/pingcap/br@v0.0.0-20200820083933-d9d6207c0aa7
github.com/pingcap/tidb@v1.1.0-beta.0.20200825092018-e52cb3714e24
```

```
github.com/pingcap/pd/v4@v4.0.0-rc.1.0.20200422143320-428acd53eba2
github.com/pingcap/tidb@v1.1.0-beta.0.20200513065557-5a0787dfa915
github.com/ngaut/unistore@v0.0.0-20200603091253-e0b717679796
github.com/pingcap/tidb@v1.1.0-beta.0.20200603101356-552e7709de0d
github.com/ngaut/unistore@v0.0.0-20200604043635-5004cdad650f
github.com/pingcap/tidb@v1.1.0-beta.0.20200604055950-efc1c154d098
github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154
github.com/pingcap/tidb@v1.1.0-beta.0.20200610060912-f12cdc42010f
github.com/pingcap/br@v0.0.0-20200617120402-56e151ad8b67
github.com/pingcap/tidb@v1.1.0-beta.0.20200721005019-f5c6e59f0daf
github.com/pingcap/br@v0.0.0-20200727092753-a475692725db
github.com/pingcap/tidb@v1.1.0-beta.0.20200803035726-41c23700d8d1
github.com/ngaut/unistore@v0.0.0-20200803051709-607d96233b1d
github.com/pingcap/br@v0.0.0-20200803052654-e6f63fc1807a
github.com/pingcap/tidb@v1.1.0-beta.0.20200805053026-cd3e5ed82671
github.com/pingcap/br@v0.0.0-20200805121136-181c081ba6ac
github.com/pingcap/tidb@v1.1.0-beta.0.20200806060043-574540aa06ba
github.com/ngaut/unistore@v0.0.0-20200806113332-5b9f73333a19
github.com/pingcap/tidb@v1.1.0-beta.0.20200810064414-d81150394f9d
github.com/pingcap/br@v0.0.0-20200820083933-d9d6207c0aa7
github.com/pingcap/tidb@v1.1.0-beta.0.20200825092018-e52cb3714e24
```

**Comment by lance6716** [comment]
BR has a very complex circular dependency with tidb. seems currently DM's update is done @GMHDBJD @csuzhangxc PTAL

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Comment by csuzhangxc** [comment]
@lance6716 do we need to cherry-pick it to release-1.0 manually?

**Comment by lance6716** [comment]
1.0 don't have a explicit dependency on pd

Xuecheng Zhang <notifications@github.com> 于 2020年8月28日周五 18:50写道：

**Comment by csuzhangxc** [comment]
OK, let it go for release-1.0 now.

**Pull request merged**
