### PR TITLE
loader: revert #1544 to reduce risks

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
We need to release v2.0.3 recently. Some improvement PRs will be reverted to reduce the risk of bugs.

### What is changed and how it works?
revert https://github.com/pingcap/dm/pull/1544

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

 - Possible performance regression

### CODE REVIEW

**Comment by lance6716** [comment]
and we should revert this "revert PR" once v2.0.3 is released?

(will review later)

**Comment by lichunzhu** [comment]
> and we should revert this "revert PR" once v2.0.3 is released?
> 
> (will review later)

Yes

**Pull request merged**
