### PR TITLE
test: fix TestPauseAndResumeSubtask

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
improve stability of `testSubTask.TestPauseAndResumeSubtask`, which fails at https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/5611/pipeline/70/

### What is changed and how it works?
wait more time

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@lance6716 should we need to cherry-pick this to _release-1.0_?

**Comment by lance6716** [comment]
> @lance6716 should we need to cherry-pick this to _release-1.0_?

Oh, I forget to cherry pick these test-fix PR 😭

**Comment by lance6716** [comment]
> @lance6716 should we need to cherry-pick this to _release-1.0_?

this PR should be cherry-pick, #785 mainly changed HA tests so need not cherry-pick

**Pull request merged**
