### PR TITLE
dep, schema: update tidb and add clustered index test

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 

update tidb, add test to make sure that
- DM didn't add clustered index comment when sync to downstream
- user could change schema tracker's clustered index by config

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
"msg": "[code=38032:class=dm-master:scope=internal:level=high], Message: some error occurs in dm-worker: ErrCode:10001 ErrClass:\"database\" ErrScope:\"downstream\" ErrLevel:\"high\" Message:\"fail to initial unit Sync of subtask task_pessimistic : database driver error\" RawCause:\"Error 1193: Unknown system variable 'tidb_enable_clustered_index'\" Workaround:\"Please check the database connection and the database config in configuration file.\" , Workaround: Please execute `query-status` to check status."

https://github.com/pingcap/dm/runs/2233469550?check_suite_focus=true

"msg": "[code=38032:class=dm-master:scope=internal:level=high], Message: some error occurs in dm-worker: ErrCode:10001 ErrClass:\"database\" ErrScope:\"downstream\" ErrLevel:\"high\" Message:\"fail to initial unit Sync of subtask test : database driver error\" RawCause:\"Error 1105: Variable 'tidb_enable_clustered_index' is a GLOBAL variable and should be set with SET GLOBAL\" Workaround:\"Please check the database connection and the database config in configuration file.\" , Workaround: Please execute `query-status` to check status."

https://github.com/pingcap/dm/runs/2233469611?check_suite_focus=true

**Comment by lichunzhu** [comment]
@lance6716 Please resolve the conflicts.

**Comment by lance6716** [comment]
> @lance6716 Please resolve the conflicts.

you could review first

**Review by 3pointer — COMMENTED** [review]
/lgtm

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
