### PR TITLE
*: move from deprecated ioutil to os and io packages

### PR DESCRIPTION
**Pull request by kallydev**
### What problem does this PR solve? 

Since dm is currently using Go 1.16, so it is safe to remove deprecated `ioutil` package, ref https://golang.org/doc/go1.16#ioutil.

### What is changed and how it works?

Remove deprecated `ioutil` package.

### Check List 

Tests 

 - Unit test

Code changes
 
Side effects

Related changes

### CODE REVIEW

**Comment by kallydev** [comment]
Hello @lance6716, do I need to change the title of the commit from `style` to `*`?

**Comment by lance6716** [comment]
> Hello @lance6716, do I need to change the title of the commit from `style` to `*`?

Hi, thanks for your contribution. 

the commit will be squashed when PR merging, so the commit title is not a problem.

According to [CONTRIBUTING.md](https://github.com/pingcap/dm/blob/master/CONTRIBUTING.md#format-of-the-commit-message), we write component names like `syncer`, `worker` instead of `style`, so I made that change to the PR title. That's not a big problem, if you insist it you can change the title back 😄

**Review by lance6716 — APPROVED** [review]

**Review by Ehco1996 — APPROVED** [review]

**Pull request merged**
