### PR TITLE
dep: update dumpling

### LINKED ISSUE #1119: track dumpling features
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

https://github.com/pingcap/dumpling/pull/157

https://github.com/pingcap/dumpling/pull/158

https://github.com/pingcap/dumpling/pull/160

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1119, part of #1130

### What is changed and how it works?
https://github.com/pingcap/dumpling/pull/157 : dumpling add `--allow-cleartext-password`
https://github.com/pingcap/dumpling/pull/158 : dumpling support dump view, but default don't dump it (need more test to default enable)
https://github.com/pingcap/dumpling/pull/160 : set default `statement-size`

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
please Approve since I made some change in CI @csuzhangxc @GMHDBJD

**Review by csuzhangxc — APPROVED** [review]

**Pull request merged**
