### PR TITLE
auto master-slave switch (#1364)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1364 to release-2.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In dm repo:
git pr https://github.com/pingcap/dm/pull/1420
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/dm.git pr/1420:release-2.0-b04afa753844
```

---

### What problem does this PR solve? 
- [x] syncer auto switch relay subdir when master-slave switch
- [x] auto test master-slave switch
- [x] auto detect master-slave switch

Tests 

 - Unit test
 - github action

### CODE REVIEW

**Review by lichunzhu — COMMENTED** [review]
/lgtm

**Comment by lance6716** [comment]
waiting https://github.com/pingcap/dm/pull/1421

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
