### PR TITLE
test: try split large integration test cases

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close https://github.com/pingcap/dm/issues/1579

### What is changed and how it works?

check if this split works, then restore `others_integration.txt` and change CI

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
a replay: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8850/pipeline

**Comment by lance6716** [comment]
replay https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8853/pipeline

**Comment by lance6716** [comment]
replay https://internal.pingcap.net/idc-jenkins/job/dm_ghpr_test/8858/

**Comment by lance6716** [comment]
I'll change the CI after this PR merged

**Comment by lance6716** [comment]
dead lock found `TestInfoEtcd`

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8862/pipeline

will fix CI stability tomorrow

**Comment by lance6716** [comment]
> dead lock found `TestInfoEtcd`
> 
> https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8862/pipeline
> 
> will fix CI stability tomorrow

caused by timeout then context canceled and no sending to two channels. WIll fix in quality reinforcement 9.

**Review by GMHDBJD — APPROVED** [review]
/lgtm

**Pull request merged**
