### PR TITLE
master: support unlock-ddl-lock after stop-task

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close https://github.com/pingcap/dm/issues/1543

### What is changed and how it works?
skip this check

### Check List 

Tests 

 - Integration test

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Review by lichunzhu — COMMENTED** [review]
/lgtm

**Comment by GMHDBJD** [comment]
Can we remove lock after stop-task?

**Comment by lance6716** [comment]
> Can we remove lock after stop-task?

since we didn't remove the checkpoint, I think we'd better also not removing ddl-lock in case of user `start-task` later

**Review by GMHDBJD — APPROVED** [review]
/lgtm

**Pull request merged**
