### PR TITLE
dep: update parser to lastest

### LINKED ISSUE #1227: Track parser support multiple table rename
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://github.com/pingcap/parser/pull/1021 , now for a single table rename, we don't have four tableName

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1227 

### What is changed and how it works?
update parser (and its needed library) to latest.

### Check List 

Tests 

 - No code

Code changes

Side effects

 - Possible performance regression

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
I suspect that tidb-tools need to update some code, to keep compatibility of https://github.com/pingcap/parser/pull/1021 . now some test failed because of sync-diff error

**Comment by csuzhangxc** [comment]
> I suspect that tidb-tools need to update some code, to keep compatibility of [pingcap/parser#1021](https://github.com/pingcap/parser/pull/1021) . now some test failed because of sync-diff error

If it's too hard to fix, we may keep parser as the current version for this 2.0.0 release.

**Comment by lance6716** [comment]
/run-all-tests

some test runs slowly (both ci and my local)

**Comment by lance6716** [comment]
for `sequence_sharding`: need to add a `sleep 10` to pass `check_sync_diff` (pass at retry 7th). I suspect that there's a performance regression, we should not merge this PR before further test

**Comment by lance6716** [comment]
replaced by https://github.com/pingcap/dm/pull/1289

**Pull request closed without merging**
