### PR TITLE
fix: reset some metrics when loader resume 

### LINKED ISSUE #459: UCP: reset some metrics of load unit when resuming
## Description

**Is your feature request related to a problem? Please describe:**

some metrics, like `data file size` in `load dump files` may display wrong after resume task because not reset in `prepareDataFiles`.

**Describe the feature you'd like:**

we need to reset them when resuming the task, like:

- calling `metricVec.DeleteLabelValues`
- or use another metric type rather than `CounterVec`.

## Score 

200

## Mentor(s)
* @csuzhangxc 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Experience with DM
* Experience with Prometheus

## Learning Materials

- [DM source reading](https://pingcap.com/blog-cn/#DM-%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB)
- [DM document](https://pingcap.com/docs-cn/stable/reference/tools/data-migration/overview/#dm-%e6%9e%b6%e6%9e%84)

### PR DESCRIPTION
**Pull request by Kuri-su**
### What problem does this PR solve? 

fix #459 

### What is changed and how it works?

* modify this metrics to gaugeVec:
  * dataFileCountor => dataFileGauge
  * tableCountor => tableGauge
  * dataSizeCountor => dataSizeGauge
* modify dm/dm-ansible/scripts/dm.json related PromQL expressions
* modify related code for metrics

### CODE REVIEW

**Comment by Kuri-su** [comment]
@csuzhangxc PTAL, thx :joy:

**Comment by csuzhangxc** [comment]
@Kuri-su I'll take a look later today. 😂

**Comment by csuzhangxc** [comment]
@lichunzhu PTAL

**Comment by lichunzhu** [comment]
@Kuri-su please update branch and run the tests

**Comment by Kuri-su** [comment]
> /award-point 200

thank you :stuck_out_tongue_winking_eye:

**Comment by you06** [comment]
The score issue has been fixed.

**Comment by csuzhangxc** [comment]
> The score issue has been fixed.

thanks

**Comment by you06** [comment]
@Kuri-su You can check it out at https://pingcap.com/community-cn/tidb-usability-challenge/

**Comment by Kuri-su** [comment]
> @Kuri-su You can check it out at https://pingcap.com/community-cn/tidb-usability-challenge/

got it

**Pull request merged**
