### PR TITLE
streamer: fix duplicate event when reparse relay using GTID

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
part of https://github.com/pingcap/dm/issues/1524

### What is changed and how it works?
when DM uses GTID and needs to return a reparse location, return last XID location so that `replaceWithHeartbeat` will be correctly calculated

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]

**Comment by GMHDBJD** [comment]
Will sync unit get duplicate events? (like gtid_event, table map event, rows event)

**Comment by lance6716** [comment]
> Will sync unit get duplicate events? (like gtid_event, table map event, rows event)

Yes, currently we rely on safe mode. I added a todo of changing the behaviour of sending binlog to "sending DML after see XID",

**Comment by GMHDBJD** [comment]
> Yes, currently we rely on safe mode. I added a todo of changing the behaviour of sending binlog to "sending DML after see XID". Do you think we should do it now?

I think we may simply return both currentGTID and latestPos for parseFile now. Otherwise, if safemode has been closed, we may have duplicate data.

**Review by GMHDBJD — APPROVED** [review]
/lgtm

**Pull request merged**
