### PR TITLE
*: fix `cannot convert type: decimal.Decimal`

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

in golang v1.13, the _Decimal decompose interface_ is introduced, see:
- https://github.com/golang/go/issues/30870
- https://github.com/golang/go/commit/683ffe09f66f0834baf039deeabe16eec6b09daa

in [shopspring/decimal@75bb2cb](https://github.com/shopspring/decimal/commit/75bb2cb98e710b1a43ff4611ebdbbbfa3d3314c3), it implements the _Decimal decompose interface_.

when executing a statement with decimal type columns, a possible execution path is:
1. https://github.com/golang/go/blob/cc8838d645/src/database/sql/sql.go#L2275
2. https://github.com/golang/go/blob/cc8838d645/src/database/sql/sql.go#L1515
3. https://github.com/golang/go/blob/cc8838d645/src/database/sql/convert.go#L177
4. https://github.com/go-sql-driver/mysql/blob/v1.4.1/connection_go18.go#L196
5. https://github.com/go-sql-driver/mysql/blob/v1.4.1/statement.go#L141
6. https://github.com/golang/go/blob/cc8838d645/src/database/sql/driver/types.go#L184

the code block

```golang
case decimalDecompose:
	return true
```

will cause the skip of the value fetching (**convert `decimal.Decimal` to `string`**) in <https://github.com/go-sql-driver/mysql/blob/v1.4.1/statement.go#L146>.

then continue the execution flow:

1. https://github.com/golang/go/blob/cc8838d645/src/database/sql/sql.go#L1538
    - (triggered with https://github.com/go-sql-driver/mysql/blob/v1.4.1/connection.go#L296)
2. https://github.com/golang/go/blob/cc8838d645/src/database/sql/sql.go#L2435
3. https://github.com/golang/go/blob/cc8838d645/src/database/sql/ctxutil.go#L65
4. https://github.com/go-sql-driver/mysql/blob/v1.4.1/connection_go18.go#L142
5. https://github.com/go-sql-driver/mysql/blob/v1.4.1/statement.go#L53
6. https://github.com/go-sql-driver/mysql/blob/v1.4.1/packets.go#L1071

another useful link https://github.com/golang/go/issues/34315.

### What is changed and how it works?

some methods can be used to fix this problem:
1. chose a _shopspring/decimal_ version without _Decimal decompose interface_ implementation
2. downgrade golang to v1.12

I chose the first one, and update _shopspring/decimal_ to https://github.com/shopspring/decimal/commit/b054a8dfd10d5e651f48ab20c6c9bee309805368. (revert _Decimal decompose interface_ implementation)

```
go get -u github.com/shopspring/decimal@b054a8dfd10d5e651f48ab20c6c9bee309805368
go mod tidy
```

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@WangXiangUSTC @amyangfei PTAL

**Comment by WangXiangUSTC** [comment]
LGTM

**Pull request merged**
