### PR TITLE
tracker: fetch ref table at CREATE LIKE and more

### LINKED ISSUE #1099: Can't track "create table t1 like t2"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

    
image

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-rc.2
        ```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1099

### What is changed and how it works?
`FetchDDLTableNames` now return all found tableNames, and some variables in `trackDDL` now become `int` represent how many tableName should used.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by lance6716** [comment]
https://docs.pingcap.com/tidb/stable/views

should we support sync view DDL now?

**Comment by csuzhangxc** [comment]
> https://docs.pingcap.com/tidb/stable/views
> 
> should we support sync `CREATE VIEW` DDL now? we drop it in`builtInSkipDDLs` now

I think we need to support it because it used by a large number of users.

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
