### PR TITLE
chaos: wait coredns more time

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

coredns may be failed in chaos mesh tests, like https://github.com/pingcap/dm/runs/1444275245?check_suite_focus=true

### What is changed and how it works?

wait more time for coredns.

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
what's the relationship of coredns ans tmate 🤔

**Comment by lance6716** [comment]
LGTM

**Comment by csuzhangxc** [comment]
> what's the relationship of coredns and tmate 🤔

coredns is used to check the K8s cluster is ready for use; tmate is used for SSH connection into the GitHub actions runner machine if failed (for debug)

**Review by lance6716 — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
