### PR TITLE
relay: support relay log in v2.0 (#1272)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1272 to release-2.0

---

### What problem does this PR solve? 
part of #1234 

### What is changed and how it works?
- [x]  support TLS in relay
- [x]  support gtid in relay

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/run-all-tests

[2020-12-18T10:44:16.411Z] [2020/12/18 18:15:42.366 +08:00] [ERROR] [db.go:175] ["execute statements failed after retry"] [task=test] [unit=load] ["worker ID"=1] [queries="[USE `many_tables_db`; INSERT INTO `t356` (`i`,`j`) VALUES\n(1,10001),\n(1,10011),\n(2,20002),\n(2,20012); UPDATE `dm_meta`.`test_loader_checkpoint` SET `offset`=109 WHERE `id` ='mysql-replica-01' AND `filename`='many_tables_db.t356.0.sql';]"] [arguments="[]"] [error="[code=10006:class=database:scope=not-set:level=high], Message: execute statement failed: begin, RawCause: invalid connection"]

forget to write a error checker for `many_tables`

**Pull request merged**
