### PR TITLE
Quality reinforcement (7): fix unstable test cases

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
- [x] DM_CASE_94, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7620/), no primary key in safe-mode cause data inconsistent. ca6a962
- [ ] testOptimist.TestOptimistLockMultipleTarget, [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7624/pipeline)
- [x] Data Race in schema tracker UT: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7713/pipeline), lance6716, https://github.com/pingcap/dm/pull/1284/commits/ac8b91f3131589f10c734997d33c5b94a6c98658
- [x] sequence_sharding: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7732/pipeline), lance6716, https://github.com/pingcap/dm/pull/1284/commits/5ed0edeeae091cc5639bd475e8ff3beeb7624b8b
- [x] handle_error: [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/7741/pipeline),gmhdbjd, 0b156b3 , ddf7c6a

### CODE REVIEW

**Comment by lance6716** [comment]
github.com/pingcap/dm/pkg/schema: jenkins, data race should has been fixed in https://github.com/pingcap/dm/commit/ac8b91f3131589f10c734997d33c5b94a6c98658

And we could plan to merge this?

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
LGTM

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
