### PR TITLE
add two shard DDL test cases

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

add more shard DDL test cases.

after this PR and #1171, all of shard DDL test cases in https://internal.pingcap.net/jira/browse/TICASE-4046 (internal only) will become closed or canceled.

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
LGTM

**Comment by csuzhangxc** [comment]
/run-all-tests

failed with some `java.nio.channels.ClosedChannelException`, 👀

**Comment by csuzhangxc** [comment]
/run-all-tests

failed with some `java.nio.channels.ClosedChannelException`

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
