### PR TITLE
Quality reinforcement (10): fix unstable test cases

### PR DESCRIPTION
**Pull request by lance6716**
previous one https://github.com/pingcap/dm/pull/1412

- [ ] ~testElectionSuite.TestElection2After1 election_test.go:108 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8918/pipeline)~ 1 second timeout for deleting a KV
- [x] "fail to register worker", dm-worker with name xx already exists [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8922/pipeline) [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8928/pipeline/87) [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8938/pipeline/)  **for this error, we should expose the original error** https://github.com/pingcap/dm/pull/1601/commits/0c59c0d9df8202bfec0ce9654106de1c6a7e181f
- [x] testSubTask.TestPauseAndResumeSubtask subtask_test.go:365 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8927/pipeline/72) https://github.com/pingcap/dm/pull/1601/commits/eadabfcad9ae9fed6256219d41d380c341633b00
- [ ] panic dm/worker/server.go:257 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8927/pipeline/76) don't know why 🤔 
- [x] testElectionSuite.TestElectionEvictLeader election_test.go:361 [jenkins](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8928/pipeline/72) https://github.com/pingcap/dm/pull/1601/commits/d95ffe8c30cdca60e130db3a42bc3ed8867de8ba

### CODE REVIEW

**Comment by lance6716** [comment]
(try new CI config)

**Comment by lance6716** [comment]
@lichunzhu PTAL

**Review by Ehco1996 — COMMENTED** [review]
/lgtm

**Pull request merged**
