### PR TITLE
Add unsafe_cleanup.yml for dm ansible

### PR DESCRIPTION
**Pull request by wilanhuang**
### What problem does this PR solve? 

    Users can unsafe_cleanup the dm module using the new adding yml file in ansible

### What is changed and how it works?

     Add a file named unsafe_cleanup.yml in ansible

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
       ansible-playbook unsafe_cleanup.yml

### CODE REVIEW

**Comment by GregoryIan** [comment]
Cool! Thanks @wilanhuang

**Comment by csuzhangxc** [comment]
@wilanhuang Thanks! Please sign the CLA.

**Comment by csuzhangxc** [comment]
CLA bot seems to have any problem, I'm going to merge the PR ignoring the CLA status

**Pull request merged**
