### PR TITLE
*: try check every returned `err` are handled

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 

close https://github.com/pingcap/dm/issues/1815

part of https://github.com/pingcap/dm/issues/1803

### What is changed and how it works?
1. precheck `backoff-max` in source config
2. precheck `do-tables`, `chunk-filesize` in task config. (we will check all fields in another PR)
3. check an error in pkg/ha/relay.go
4. dump unit's panic issue

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Review by GMHDBJD — APPROVED** [review]
LGTM. Will the new linter be integrated?

**Comment by lance6716** [comment]
> Will the new linter be integrated?

the new linter has many bad cases 😂 need more development

**Review by 3pointer — APPROVED** [review]
LGTM

**Pull request merged**
