### PR TITLE
log: set log level for embed etcd and ddl tracker

### LINKED ISSUE #495: reduce TiDB's log in dm-worker && etcd's log in dm-master
## Description

**Is your feature request related to a problem? Please describe:**

- In dm-worker, we use some code of tidb to execute DDL to keep the table's schema information and will output tidb's log in dm-worker's log file.

- In dm-master, we use etcd to save cluster's meta information and will output etcd's log in dm-master's log file.

The most of both etcd and tidb's log is useless and make logs too numerous.

**Describe the feature you'd like:**

Only print the error log of etcd and tidb, or output their log to another file.

## Score 

300

## Mentor(s)
* @csuzhangxc 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Experience with DM

## Learning Materials

 * [The document for DM HA](https://docs.google.com/document/d/1zFCqZqxd5AgOsyIWGZ1fEPEuRMhKH7584tTNQ60l4Ig/edit#heading=h.h7g97d4262qg) in Chinese.

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
close #495 

### What is changed and how it works?
- set error log level for embed etcd
- set error log level for global logger which currently only use by schemaTracker

Tests 

 - Manually check the log

### CODE REVIEW

**Comment by lance6716** [comment]
feel relief to know I'm not the only one failed CI

**Comment by GMHDBJD** [comment]
> feel relief to know I'm not the only one failed CI

Don't worry. You can take a look at [TiDB's CI](https://github.com/pingcap/tidb/pulls). 😂

**Comment by lance6716** [comment]
LGTM

**Pull request merged**
