### PR TITLE
test: when VIP upstream switching, continue from relay.meta

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
just a test, to verify https://github.com/pingcap/dm/issues/1524

### What is changed and how it works?

check we continue on latest relay log (`.000002`)

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
https://github.com/pingcap/dm/actions/runs/685655448

```
[2021/03/25 07:20:24.853 +00:00] [INFO] [task_checker.go:340] ["dispatch auto resume relay"] [component="task checker"]
[2021/03/25 07:20:24.882 +00:00] [INFO] [relay.go:633] ["adjusted meta to start pos"] [component="relay log"] ["start pos"="{\"Name\":\"\",\"Pos\":4}"] ["start pos's binlog gtid"=62408efe-8d3a-11eb-8bbe-0242ac1c8006:1]
```
 test in this PR did not discover the outdated relay.meta

**Review by GMHDBJD — APPROVED** [review]
/lgtm

**Pull request merged**
