### PR TITLE
dmctl: refine commands' usage text

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

refine dmctl comands' usage text

### What is changed and how it works?

refine usage suggestion from I18N team in https://github.com/pingcap/docs-cn/pull/1878.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
 	1. run dmctl
 	2. observe the output of usage

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@amyangfei @WangXiangUSTC PTAL

**Comment by csuzhangxc** [comment]
> will all output be changed to `DM-worker`, such as
> https://github.com/pingcap/dm/blob/master/dm/ctl/master/break_ddl_lock.go#L54

sounds good. should we need to changed to `DM-worker` for _error class_?

**Comment by amyangfei** [comment]
> > will all output be changed to `DM-worker`, such as
> > https://github.com/pingcap/dm/blob/master/dm/ctl/master/break_ddl_lock.go#L54
> 
> sounds good. should we need to changed to `DM-worker` for _error class_?

I feel ok to change to `DM-worker` in `error class`. What about other guys' opinion @GregoryIan @WangXiangUSTC

**Comment by csuzhangxc** [comment]
@amyangfei changed to `DM-worker` for dmctl's command direct output, but not change other places in https://github.com/pingcap/dm/pull/296/commits/da2793e1e59b4488ea21c93900e74b2badb60b99.

other places including:
- error class
- log
- some output in DM-ansible

**Pull request merged**
