### PR TITLE
tracker: don't execute add FK on tracker 

### LINKED ISSUE #1056: reference table not exists when add foreign key statement is the first statement that table in syncer
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```
start task
alter table tb1 add constraint foreign key (a) references tb2(a);
```

2. What did you expect to see?
worker runs well
3. What did you see instead?
```
{
                                "ErrCode": 44006,
                                "ErrClass": "schema-tracker",
                                "ErrScope": "internal",
                                "ErrLevel": "high",
                                "Message": "startLocation: [position: (mysql-bin.000001, 987), gtid-set: 90ef7875-f829-11ea-a36c-0242ac110002:1-4], endLocation: [position: (mysql-bin.000001, 1154), gtid-set: 90ef7875-f829-11ea-a36c-0242ac110002:1-5]: cannot track DDL: ALTER TABLE `handle_error`.`tb1` ADD CONSTRAINT FOREIGN KEY (`a`) REFERENCES `handle_error`.`ta`(`a`)",
                                "RawCause": "[schema:1146]Table 'handle_error.ta' doesn't exist",
                                "Workaround": ""
}
```
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        master
        ```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1056

### What is changed and how it works?
if a DDL is "alter atble add FK", don't execute it on tracker

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
/run-all-tests

failed test recorded in https://github.com/pingcap/dm/pull/1046

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
PTAL @GMHDBJD . I'm going to fix https://github.com/pingcap/dm/issues/1099 based on this part, in order to reduce confilct

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
